In [2]:
import pickle

import numpy as np


In [38]:
with open("my-saved-model.pt", "rb") as file:
    model = pickle.load(file)
with open("my-saved-model.pt", "wb") as file:
    pickle.dump(model,file)

In [5]:
b = []
b.append(1)
b.append(2)
b.append(6)
b.append(2)

b.append(1)
b.append(5)


a = np.stack(b)

In [6]:
print(a)

[1 2 6 2 1 5]


In [7]:
def fun(a,b):
    print(a)
    return a+b

In [64]:
weigths = np.ones((17,6))*[.2, .2, .2, .2, .1, .1]
model = weigths/weigths.sum()

print(weigths)

1.0
[[0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]]


In [9]:
print(a)

[1 2 6 2 1 5]


In [11]:
print(np.argmax(a))

2


In [12]:
a = np.ones((3840,5))

In [14]:
print(a.shape)

(3840, 5)


[[1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [131]:
a = np.array([[True, False, False, True],[False, True, True, True]])

In [132]:
coins = [(1,(2,3)),(6,(3,2)),(4,(1,1))]

In [136]:
a[0,1]

False

In [137]:
a[xy[0],xy[1]]

True

In [114]:
d=5
d-=3
print(t)

(6, 1)


In [84]:
len(coins)

1

In [140]:
for   i in [-1,+1]:
    print(i)

-1
1


In [149]:
(x,y)=(0,0)

for num, (i,j) in enumerate([(x + h, y) for h in [-1, 1]] + [(x, y + h) for h in [-1, 1]]):
    print(num)
    print((i,j))
    

0
(-1, 0)
1
(1, 0)
2
(0, -1)
3
(0, 1)


In [5]:
array= np.ones((4,4,4,4,5,3,5))

In [38]:
b = tuple((0,1,2,1,1,1))
print(b)

(0, 1, 2, 1, 1, 1)


In [39]:
array[b]

array([1., 1., 1., 1., 1.])

In [33]:
c = np.array([0,0,0,1,2,1])

In [40]:
d = tuple(c)
print(d)
print(array[d])

(0, 0, 0, 1, 2, 1)
[1. 1. 1. 1. 1.]
