In [66]:
import pickle

import numpy as np
from collections import namedtuple, deque
import random

In [190]:
with open("my-saved-model.pt", "rb") as file:
    model = pickle.load(file)
print(model)

[-4.1494017  -4.1494017  -4.1494017  -4.1494017  -4.14959509 -4.14959509]


In [81]:
b = []
b.append(1)
b.append(2)
b.append(6)
b.append(2)

b.append(1)
b.append(5)


a = np.stack(b)

In [82]:
print(a)

[1 2 6 2 1 5]


In [83]:
def fun(a,b):
    print(a)
    return a+b

In [84]:
weigths = np.ones((17,6))*[.2, .2, .2, .2, .1, .1]
model = weigths/weigths.sum()

print(weigths)

[[0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.1 0.1]]


In [85]:
print(a)

[1 2 6 2 1 5]


In [86]:
print(np.argmax(a))

2


In [87]:
a = np.ones((3840,5))

In [88]:
print(a.shape)

(3840, 5)


In [89]:
a = np.array([[True, False, False, True],[False, True, True, True]])

In [90]:
coins = [(1,(2,3)),(6,(3,2)),(4,(1,1))]

In [91]:
a[0,1]

False

In [20]:
len(coins)

3

In [21]:
for   i in [-1,+1]:
    print(i)

-1
1


In [22]:
(x,y)=(0,0)

for num, (i,j) in enumerate([(x + h, y) for h in [-1, 1]] + [(x, y + h) for h in [-1, 1]]):
    print(num)
    print((i,j))
    

0
(-1, 0)
1
(1, 0)
2
(0, -1)
3
(0, 1)


In [23]:
array= np.ones((4,4,4,4,5,3,5))

In [24]:
b = tuple((0,1,2,1,1,1))
print(b)

(0, 1, 2, 1, 1, 1)


In [25]:
array[b]

array([1., 1., 1., 1., 1.])

In [97]:
c = np.array([0,0,0,1,2,1])

print(np.max(c))

2


In [27]:
d = tuple(c)
print(d)
print(array[d])

(0, 0, 0, 1, 2, 1)
[1. 1. 1. 1. 1.]


In [28]:
a = 1==1==1==2

In [29]:
print(a)

False


In [32]:
print(np.argmax(d))

4


In [36]:
x=3
if 1<x<7:
    print(1)

1


In [43]:
if(False): x=0
#comment
elif(3<9):
    print('f')

f


In [46]:
x = False


if not x:
    print('lol')

lol


In [98]:
Transition =namedtuple('Transition',('state','action','next_state','reward'))

In [99]:
transitions = deque(maxlen=3)

In [107]:
transitions.append(Transition(2,2,2,90))

In [108]:
a =transitions.pop()[0]
print(a)

2


In [70]:
print(random.random())

0.5223075322684599


In [75]:
transitions[0][0]

5

In [196]:
a=np.ones((4,4,4,4,5,3))

b = tuple(np.array([0,0,0,0,0,0]))

c = tuple(np.zeros(6,dtype='int'))
print(b)

(0, 0, 0, 0, 0, 0)


In [176]:
print(a[c])

1.0


In [177]:
model =np.ones((4,4,4,4,5,3,6))*[.25, .25, .25, .25, .0, .0]

In [169]:



model[b] = [.5,.5,0,0,0,0]

print(model[0,0,0,0,0,1])

[0.5 0.5 0.  0.  0.  0. ]


In [170]:
print(model[0,0,0,0,0,1])

[0.5 0.5 0.  0.  0.  0. ]


In [171]:
with open("test.pt", "rb") as file:
    model = pickle.load(file)

In [194]:
model[0,0,0,0,0,1]=model[0,0,0,0,0,1]+2

In [195]:
print(model[0,0,0,0,0,1])

[2.25 2.25 2.25 2.25 2.   2.  ]


In [178]:

model[b] = model[b] + 0.1*(4+0.9*(np.max(model[1,0,0,0,0,0]))-model[b])

In [199]:
model[b][1]

0.25

In [192]:
with open("my-saved-model.pt", "rb") as file:
    model = pickle.load(file)


In [200]:
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

In [204]:
actions = {'UP': 0, 'RIGHT': 1, 'DOWN': 2,'LEFT': 3 , 'WAIT': 4, 'BOMB': 5}

In [207]:
string = 'WAIT'


actions[string]

4

In [208]:
max([1,2,3,545])

545