In [2]:
import pickle

import numpy as np
from collections import namedtuple, deque
import random

In [113]:
with open("my-saved-model.pt", "rb") as file:
    model = pickle.load(file)
print(model[1,0,1,1,2,1])


[-100.87393836    0.40349527 -100.83487974 -100.86615972    0.14574672
 -117.01320261]


In [3]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))
action = {'UP': 0, 'RIGHT': 1, 'DOWN': 2,'LEFT': 3 , 'WAIT': 4, 'BOMB': 5}

In [4]:
transitions = deque(maxlen=3)

In [5]:
transitions.append([[3,56,9],'UP',3,50])

In [6]:
actions = np.array([old_state for (old_state,a,new_state,reward) in transitions])

In [7]:
print(np.max(actions, axis=1))

[56]


In [8]:
gamma_exp = np.array([0.9**k for k in range(0,4)])

In [9]:
print(np.sum(gamma_exp*np.array([0,-4,0,-4])))

-6.516


In [68]:
a = [(1,2),(3,2),(0,8),(7,7)]

In [71]:
if (0,8) in a:
    print('IN')


IN


In [17]:
for num, (i,j) in enumerate([(x + h, y) for h in [-1, 1]] + [(x, y + h) for h in [-1, 1]]):   
    print(i,j)

-1 0
1 0
0 -1
0 1


In [32]:

ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
np.random.choice(ACTIONS, p=[.25, .25, .25, .25, .0, .0])

'UP'

In [1]:
def fun(a):
    return a,a,True

In [2]:
c,d,e = fun(3)

In [3]:
print(e)

True


In [103]:
matrix = np.ones((17,17))*5

matrix[1,2]=1
matrix[2,3]=1
matrix[15,8]=1

print(matrix)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 1. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 1. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 1. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [104]:
array = [(x,y) for (x,y) in np.array(np.where(matrix+matrix<10)).T]

In [105]:
print(array)

[(1, 2), (2, 3), (15, 8)]


In [106]:
(x,y)=(1,1)

array = [(x + h, y) for h in range(-3, 4)] + [(x, y + h) for h in range(-3, 4)]


print(array)

[(-2, 1), (-1, 1), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (1, -2), (1, -1), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4)]


In [107]:
hit =[]

hit = hit+[(1,2)]
hit = hit+[(1,2)]
hit = hit+[(1,5)]

test = [(1,5)]

In [108]:
print(hit)

[(1, 2), (1, 2), (1, 5)]


In [109]:
def fun(a,b,c):
    return 3


fun(2,(1,2)[0],(1,2)[1])

3

In [110]:

array = [(i,j) for (i,j) in hit if matrix[i,j]<5]

In [111]:
print(array)

[(1, 2), (1, 2)]


In [112]:
(matrix+matrix)[1,2]

2.0