In [2]:
import pickle

import numpy as np
from collections import namedtuple, deque
import random

In [28]:
with open("my-saved-model.pt", "rb") as file:
    model = pickle.load(file)
print(model[1,0,0,1,0,1])

[ -5.00199593  -5.00063954 -19.1794947  -42.06578382  -4.99999222
 -72.18137751]


In [146]:
Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))
action = {'UP': 0, 'RIGHT': 1, 'DOWN': 2,'LEFT': 3 , 'WAIT': 4, 'BOMB': 5}

In [147]:
transitions = deque(maxlen=3)

In [155]:
transitions.append(Transition([3,5,9],'DOWN',[3,5,9],50))






In [156]:
print(transitions)

deque([Transition(state=[3, 5, 9], action='DOWN', next_state=[3, 5, 9], reward=50), Transition(state=[3, 5, 9], action='DOWN', next_state=[3, 5, 9], reward=50), Transition(state=[3, 5, 9], action='DOWN', next_state=[3, 5, 9], reward=50)], maxlen=3)


In [6]:
actions = np.array([old_state for (old_state,a,new_state,reward) in transitions])

In [7]:
print(np.max(actions, axis=1))

[56]


In [8]:
gamma_exp = np.array([0.9**k for k in range(0,4)])

In [9]:
print(np.sum(gamma_exp*np.array([0,-4,0,-4])))

-6.516


In [68]:
a = [(1,2),(3,2),(0,8),(7,7)]

In [71]:
if (0,8) in a:
    print('IN')


IN


In [17]:
for num, (i,j) in enumerate([(x + h, y) for h in [-1, 1]] + [(x, y + h) for h in [-1, 1]]):   
    print(i,j)

-1 0
1 0
0 -1
0 1


In [32]:

ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']
np.random.choice(ACTIONS, p=[.25, .25, .25, .25, .0, .0])

'UP'

In [1]:
def fun(a):
    return a,a,True

In [2]:
c,d,e = fun(3)

In [3]:
print(e)

True


In [210]:
bomb_map = np.ones((17,17))*5
explosion_map =np.zeros((17,17))

explosion_map[]

bomb_map[1,3]=3
print(bomb_map)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 3. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [159]:
print(np.max(matrix[None]))

5.0


In [105]:
print(array)

[(1, 2), (2, 3), (15, 8)]


In [106]:
(x,y)=(1,1)

array = [(x + h, y) for h in range(-3, 4)] + [(x, y + h) for h in range(-3, 4)]


print(array)

[(-2, 1), (-1, 1), (0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (1, -2), (1, -1), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4)]


In [122]:
hit =[]

hit = hit+[(1,2)]
hit = hit+[(1,2)]
hit = hit+[(2,3)]

test = [(1,5)]

In [123]:
print(hit)

[(1, 2), (1, 2), (2, 3)]


In [124]:
def fun(a,b,c):
    return 3


fun(2,(1,2)[0],(1,2)[1])

3

In [125]:

array = [(i,j) for (i,j) in hit if matrix[i,j]<5]

In [126]:
print(array)

[(1, 2), (1, 2), (2, 3)]


In [130]:
trarray= ['TEST','FLEST','CHEST','MEST']

In [137]:
grarray = [i for i in trarray if (i != 'TEST' and i!='MEST')]

In [138]:
print(grarray)

['FLEST', 'CHEST']


In [140]:
if 'TEST' in trarray:
    print('yes')

yes


In [200]:
action = 'ACTION'

In [201]:
bl = action!='ACTION'

In [206]:
(x,y)=(0,0)

In [208]:
for num, (i,j) in enumerate([(x + h, y) for h in [-1, 1]] + [(x, y + h) for h in [-1, 1]]):
    print(i,j)

-1 0
1 0
0 -1
0 1


In [213]:
p = [(x,y) for (x,y) in np.array(np.where(bomb_map+explosion_map!=5)).T]

In [214]:
print(p)

[(1, 3)]


In [216]:
x = 5

if(x<7):
    print(9)
elif(x<9):
    print(46)

9


In [300]:
(x,y)=(0,0)
array =[(x + h, y) for h in range(-3, 4) ] + [(x, y + h) for h in range(-3, 4)]

In [310]:
array=[]
for h in range(0, 4):
    
    array.append((x + h, y))

In [311]:
print(array)

[(0, 0), (1, 0), (2, 0), (3, 0)]


In [309]:
print(array)

[(-1, 0), (-2, 0), (-3, 0)]


In [ ]:
mat = np.ones((6,6))